language: go
services:
  - docker
env:
  - CGO_ENABLE=0
install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
script:
  - golangci-lint run ./...
  - go test ./...
  - go build ./...
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USER" --password-stdin
  - ls -lah
deploy:
  skip_cleanup: true
  provider: script
  script:
    - docker build . -t helloworld:"$TRAVIS_COMMIT" && docker tag helloworld:"$TRAVIS_COMMIT"  "$DOCKER_REGISTRY"/helloworld:"$TRAVIS_COMMIT" && docker push "$DOCKER_REGISTRY"/helloworld:"$TRAVIS_COMMIT"
  on:
    branch: master
notifications:
  email: false
