language: go
install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
script:
  - golangci-lint run ./...
  - go test ./...
  - go build ./...
notifications:
  email: false
